# %% This file contains some parsing functions.
import pandas as pd
from os import listdir, path
from natsort import natsorted


def combine_results(input_folder, output_file):
    """ Combines all separate trajectories in input_folder generated by
        old algorithm into one for easy comparing. 
    """
    files = natsorted([file for file in listdir(input_folder) if file[-4:] == '.csv'])
    df_list = [pd.read_csv(path.join(input_folder, file), delimiter=':') for file in files]
   
    # adding a unique ID for each fly, doesn't matter which arena
    for fly_ID, df in enumerate(df_list):
        df['ID'] = fly_ID
    
    df = pd.concat(df_list)
    df = df.rename(columns={'numFrame': 'frame', 'X': 'x', 'Y': 'y', 'VX': 'vx', 'VY': 'vy', 'T/A': 'touch'}) #renaming columns
    df = df.reset_index()
    df.to_hdf(output_file, key='data', complib='blosc', complevel=9) # maximum compression

